export const COUNTRY_MAP = {
  algeria:        { label: 'Aljazair',         flag: '🇩🇿', code: 'DZ' },
  australia:      { label: 'Australia',        flag: '🇦🇺', code: 'AU' },
  austria:        { label: 'Austria',          flag: '🇦🇹', code: 'AT' },
  bangladesh:     { label: 'Bangladesh',       flag: '🇧🇩', code: 'BD' },
  belgium:        { label: 'Belgia',           flag: '🇧🇪', code: 'BE' },
  brunei:         { label: 'Brunei',           flag: '🇧🇳', code: 'BN' },
  bulgaria:       { label: 'Bulgaria',         flag: '🇧🇬', code: 'BG' },
  canada:         { label: 'Kanada',           flag: '🇨🇦', code: 'CA' },
  china:          { label: 'Tiongkok',         flag: '🇨🇳', code: 'CN' },
  croatia:        { label: 'Kroasia',          flag: '🇭🇷', code: 'HR' },
  czech_republic: { label: 'Republik Ceko',    flag: '🇨🇿', code: 'CZ' },
  denmark:        { label: 'Denmark',          flag: '🇩🇰', code: 'DK' },
  egypt:          { label: 'Mesir',            flag: '🇪🇬', code: 'EG' },
  finland:        { label: 'Finlandia',        flag: '🇫🇮', code: 'FI' },
  france:         { label: 'Prancis',          flag: '🇫🇷', code: 'FR' },
  germany:        { label: 'Jerman',           flag: '🇩🇪', code: 'DE' },
  hong_kong:      { label: 'Hong Kong',        flag: '🇭🇰', code: 'HK' },
  hungary:        { label: 'Hungaria',         flag: '🇭🇺', code: 'HU' },
  india:          { label: 'India',            flag: '🇮🇳', code: 'IN' },
  iran:           { label: 'Iran',             flag: '🇮🇷', code: 'IR' },
  italy:          { label: 'Italia',           flag: '🇮🇹', code: 'IT' },
  japan:          { label: 'Jepang',           flag: '🇯🇵', code: 'JP' },
  jordan:         { label: 'Yordania',         flag: '🇯🇴', code: 'JO' },
  south_korea:    { label: 'Korea Selatan',    flag: '🇰🇷', code: 'KR' },
  north_korea:    { label: 'Korea Utara',      flag: '🇰🇵', code: 'KP' },
  kuwait:         { label: 'Kuwait',           flag: '🇰🇼', code: 'KW' },
  luxembourg:     { label: 'Luksemburg',       flag: '🇱🇺', code: 'LU' },
  malaysia:       { label: 'Malaysia',         flag: '🇲🇾', code: 'MY' },
  mexico:         { label: 'Meksiko',          flag: '🇲🇽', code: 'MX' },
  mongolia:       { label: 'Mongolia',         flag: '🇲🇳', code: 'MN' },
  morocco:        { label: 'Maroko',           flag: '🇲🇦', code: 'MA' },
  netherlands:    { label: 'Belanda',          flag: '🇳🇱', code: 'NL' },
  new_zealand:    { label: 'Selandia Baru',    flag: '🇳🇿', code: 'NZ' },
  norway:         { label: 'Norwegia',         flag: '🇳🇴', code: 'NO' },
  pakistan:       { label: 'Pakistan',         flag: '🇵🇰', code: 'PK' },
  philippines:    { label: 'Filipina',         flag: '🇵🇭', code: 'PH' },
  poland:         { label: 'Polandia',         flag: '🇵🇱', code: 'PL' },
  portugal:       { label: 'Portugal',         flag: '🇵🇹', code: 'PT' },
  qatar:          { label: 'Qatar',            flag: '🇶🇦', code: 'QA' },
  romania:        { label: 'Romania',          flag: '🇷🇴', code: 'RO' },
  russia:         { label: 'Rusia',            flag: '🇷🇺', code: 'RU' },
  saudi_arabia:   { label: 'Arab Saudi',       flag: '🇸🇦', code: 'SA' },
  seychelles:     { label: 'Seychelles',       flag: '🇸🇨', code: 'SC' },
  singapore:      { label: 'Singapura',        flag: '🇸🇬', code: 'SG' },
  slovakia:       { label: 'Slovakia',         flag: '🇸🇰', code: 'SK' },
  south_africa:   { label: 'Afrika Selatan',   flag: '🇿🇦', code: 'ZA' },
  spain:          { label: 'Spanyol',          flag: '🇪🇸', code: 'ES' },
  sri_lanka:      { label: 'Sri Lanka',        flag: '🇱🇰', code: 'LK' },
  sudan:          { label: 'Sudan',            flag: '🇸🇩', code: 'SD' },
  sweden:         { label: 'Swedia',           flag: '🇸🇪', code: 'SE' },
  switzerland:    { label: 'Swiss',            flag: '🇨🇭', code: 'CH' },
  syria:          { label: 'Suriah',           flag: '🇸🇾', code: 'SY' },
  taiwan:         { label: 'Taiwan',           flag: '🇹🇼', code: 'TW' },
  thailand:       { label: 'Thailand',         flag: '🇹🇭', code: 'TH' },
  tunisia:        { label: 'Tunisia',          flag: '🇹🇳', code: 'TN' },
  turkey:         { label: 'Turki',            flag: '🇹🇷', code: 'TR' },
  uae:            { label: 'Uni Emirat Arab',  flag: '🇦🇪', code: 'AE' },
  ukraine:        { label: 'Ukraina',          flag: '🇺🇦', code: 'UA' },
  uk:             { label: 'Inggris',          flag: '🇬🇧', code: 'GB' },
  usa:            { label: 'Amerika Serikat',  flag: '🇺🇸', code: 'US' },
  uzbekistan:     { label: 'Uzbekistan',       flag: '🇺🇿', code: 'UZ' },
  venezuela:      { label: 'Venezuela',        flag: '🇻🇪', code: 'VE' },
  vietnam:        { label: 'Vietnam',          flag: '🇻🇳', code: 'VN' },
  other:          { label: 'Negara Lainnya',   flag: '🌍', code: '···' },
}

export default function CountryChip({ country }) {
  const c = COUNTRY_MAP[country]
  if (!c) return <span className="tiq-country">{country}</span>
  return (
    <span className="tiq-country">
      <span className="tiq-flag">{c.flag}</span>
      <span>{c.label}</span>
    </span>
  )
}
