# Generated by Django 4.2.16 on 2026-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='country',
            field=models.CharField(choices=[('algeria', 'Aljazair'), ('australia', 'Australia'), ('austria', 'Austria'), ('bangladesh', 'Bangladesh'), ('belgium', 'Belgia'), ('brunei', 'Brunei'), ('bulgaria', 'Bulgaria'), ('canada', 'Kanada'), ('china', 'Tiongkok'), ('croatia', 'Kroasia'), ('czech_republic', 'Republik Ceko'), ('denmark', 'Denmark'), ('egypt', 'Mesir'), ('finland', 'Finlandia'), ('france', 'Prancis'), ('germany', 'Jerman'), ('hong_kong', 'Hong Kong'), ('hungary', 'Hungaria'), ('india', 'India'), ('iran', 'Iran'), ('italy', 'Italia'), ('japan', 'Jepang'), ('jordan', 'Yordania'), ('south_korea', 'Korea Selatan'), ('north_korea', 'Korea Utara'), ('kuwait', 'Kuwait'), ('luxembourg', 'Luksemburg'), ('malaysia', 'Malaysia'), ('mexico', 'Meksiko'), ('mongolia', 'Mongolia'), ('morocco', 'Maroko'), ('netherlands', 'Belanda'), ('new_zealand', 'Selandia Baru'), ('norway', 'Norwegia'), ('pakistan', 'Pakistan'), ('philippines', 'Filipina'), ('poland', 'Polandia'), ('portugal', 'Portugal'), ('qatar', 'Qatar'), ('romania', 'Romania'), ('russia', 'Rusia'), ('saudi_arabia', 'Arab Saudi'), ('seychelles', 'Seychelles'), ('singapore', 'Singapura'), ('slovakia', 'Slovakia'), ('south_africa', 'Afrika Selatan'), ('spain', 'Spanyol'), ('sri_lanka', 'Sri Lanka'), ('sudan', 'Sudan'), ('sweden', 'Swedia'), ('switzerland', 'Swiss'), ('syria', 'Suriah'), ('taiwan', 'Taiwan'), ('thailand', 'Thailand'), ('tunisia', 'Tunisia'), ('turkey', 'Turki'), ('uae', 'Uni Emirat Arab'), ('ukraine', 'Ukraina'), ('uk', 'Inggris'), ('usa', 'Amerika Serikat'), ('uzbekistan', 'Uzbekistan'), ('venezuela', 'Venezuela'), ('vietnam', 'Vietnam'), ('other', 'Negara Lainnya')], max_length=50),
        ),
    ]
