const _c = (nameId, divGen, divQual, interest, royalty) => ({
  technical_services:  { rate: 0,        basis: `Art. 7 P3B Indonesia-${nameId}` },
  royalties:           { rate: royalty,   basis: `Art. 12 P3B Indonesia-${nameId}` },
  dividends_general:   { rate: divGen,    basis: `Art. 10(2)(b) P3B Indonesia-${nameId}` },
  dividends_qualified: { rate: divQual,   basis: `Art. 10(2)(a) P3B Indonesia-${nameId}` },
  interest:            { rate: interest,  basis: `Art. 11 P3B Indonesia-${nameId}` },
})

export const TREATY_RATES = {
  algeria:        _c('Aljazair',        15,    15,    15,    15),
  australia:      _c('Australia',       15,    10,    10,    10),
  austria:        _c('Austria',         15,    10,    10,    20),
  bangladesh:     _c('Bangladesh',      15,    10,    10,    20),
  belgium:        _c('Belgia',          15,    15,    10,    20),
  brunei:         _c('Brunei',          15,    15,    15,    20),
  bulgaria:       _c('Bulgaria',        15,    15,    10,    20),
  canada:         _c('Kanada',          15,    15,    15,    20),
  china:          _c('Tiongkok',        10,    10,    10,    20),
  croatia:        _c('Kroasia',         10,    10,    10,    20),
  czech_republic: _c('Republik Ceko',   15,    10,  12.5,    20),
  denmark:        _c('Denmark',         20,    10,    10,    20),
  egypt:          _c('Mesir',           15,    15,    15,    20),
  finland:        _c('Finlandia',       15,    10,    10,    10),
  france:         _c('Prancis',         15,    10,    15,    10),
  germany:        _c('Jerman',          15,    10,    10,    10),
  hong_kong:      _c('Hong Kong',       10,     5,    10,    20),
  hungary:        _c('Hungaria',        15,    15,    15,    20),
  india:          _c('India',           10,    10,    10,    20),
  iran:           _c('Iran',             7,     7,    10,    12),
  italy:          _c('Italia',          15,    10,    10,    10),
  japan:          _c('Jepang',          15,    10,    10,    10),
  jordan:         _c('Yordania',        10,    10,    10,    20),
  south_korea:    _c('Korea Selatan',   15,    10,    10,    20),
  north_korea:    _c('Korea Utara',     10,    10,    10,    20),
  kuwait:         _c('Kuwait',          10,    10,     5,    20),
  luxembourg:     _c('Luksemburg',      15,    10,    10,  12.5),
  malaysia:       _c('Malaysia',        10,    10,    10,    20),
  mexico:         _c('Meksiko',         10,    10,    10,    20),
  mongolia:       _c('Mongolia',        10,    10,    10,    20),
  morocco:        _c('Maroko',          10,    10,    10,    20),
  netherlands:    _c('Belanda',         15,     5,    10,    10),
  new_zealand:    _c('Selandia Baru',   15,    15,    10,    20),
  norway:         _c('Norwegia',        15,    15,    10,    10),
  pakistan:       _c('Pakistan',        15,    10,    15,    20),
  philippines:    _c('Filipina',        20,    15,    15,    15),
  poland:         _c('Polandia',        15,    10,    10,    20),
  portugal:       _c('Portugal',        10,    10,    10,    20),
  qatar:          _c('Qatar',           10,    10,    10,     5),
  romania:        _c('Romania',         15,  12.5,  12.5,    15),
  russia:         _c('Rusia',           15,    15,    15,    20),
  saudi_arabia:   _c('Arab Saudi',      20,    20,    20,    20),
  seychelles:     _c('Seychelles',      10,    10,    10,    20),
  singapore:      _c('Singapura',       15,    10,    10,     8),
  slovakia:       _c('Slovakia',        10,    10,    10,    10),
  south_africa:   _c('Afrika Selatan',  15,    10,    10,    20),
  spain:          _c('Spanyol',         15,    10,    10,    20),
  sri_lanka:      _c('Sri Lanka',       15,    15,    15,    20),
  sudan:          _c('Sudan',           10,    10,    15,    20),
  sweden:         _c('Swedia',          15,    10,    10,    10),
  switzerland:    _c('Swiss',           15,    10,    10,    20),
  syria:          _c('Suriah',          10,    10,    10,    20),
  taiwan:         _c('Taiwan',          10,    10,    10,    20),
  thailand:       _c('Thailand',        15,    15,    15,    15),
  tunisia:        _c('Tunisia',         12,    12,    12,    20),
  turkey:         _c('Turki',           15,    10,    10,    20),
  uae:            _c('Uni Emirat Arab', 10,    10,     5,     5),
  ukraine:        _c('Ukraina',         15,    10,    10,    20),
  uk:             _c('Inggris',         15,    10,    10,    10),
  usa:            _c('AS',              15,    10,    10,    10),
  uzbekistan:     _c('Uzbekistan',      10,    10,    10,    20),
  venezuela:      _c('Venezuela',       15,    10,    10,    20),
  vietnam:        _c('Vietnam',         15,    15,    15,    20),
}

export const DOMESTIC_RATE = 20

export function getTreatyRate(country, incomeType) {
  return TREATY_RATES[country]?.[incomeType] || null
}

export function calculateTaxSavings(amountIdr, treatyRate, domesticRate = DOMESTIC_RATE) {
  const savingsRate = (domesticRate - treatyRate) / 100
  return Math.max(amountIdr * savingsRate, 0)
}

export function formatIDR(amount) {
  if (amount == null) return 'Rp 0'
  const num = typeof amount === 'string' ? parseFloat(amount) : amount
  return 'Rp ' + num.toLocaleString('id-ID', { maximumFractionDigits: 0 })
}

export function formatPercent(rate) {
  return `${rate}%`
}

export const COUNTRIES = [
  { value: 'algeria',        label: 'Aljazair 🇩🇿' },
  { value: 'australia',      label: 'Australia 🇦🇺' },
  { value: 'austria',        label: 'Austria 🇦🇹' },
  { value: 'bangladesh',     label: 'Bangladesh 🇧🇩' },
  { value: 'belgium',        label: 'Belgia 🇧🇪' },
  { value: 'brunei',         label: 'Brunei 🇧🇳' },
  { value: 'bulgaria',       label: 'Bulgaria 🇧🇬' },
  { value: 'canada',         label: 'Kanada 🇨🇦' },
  { value: 'china',          label: 'Tiongkok 🇨🇳' },
  { value: 'croatia',        label: 'Kroasia 🇭🇷' },
  { value: 'czech_republic', label: 'Republik Ceko 🇨🇿' },
  { value: 'denmark',        label: 'Denmark 🇩🇰' },
  { value: 'egypt',          label: 'Mesir 🇪🇬' },
  { value: 'finland',        label: 'Finlandia 🇫🇮' },
  { value: 'france',         label: 'Prancis 🇫🇷' },
  { value: 'germany',        label: 'Jerman 🇩🇪' },
  { value: 'hong_kong',      label: 'Hong Kong 🇭🇰' },
  { value: 'hungary',        label: 'Hungaria 🇭🇺' },
  { value: 'india',          label: 'India 🇮🇳' },
  { value: 'iran',           label: 'Iran 🇮🇷' },
  { value: 'italy',          label: 'Italia 🇮🇹' },
  { value: 'japan',          label: 'Jepang 🇯🇵' },
  { value: 'jordan',         label: 'Yordania 🇯🇴' },
  { value: 'south_korea',    label: 'Korea Selatan 🇰🇷' },
  { value: 'north_korea',    label: 'Korea Utara 🇰🇵' },
  { value: 'kuwait',         label: 'Kuwait 🇰🇼' },
  { value: 'luxembourg',     label: 'Luksemburg 🇱🇺' },
  { value: 'malaysia',       label: 'Malaysia 🇲🇾' },
  { value: 'mexico',         label: 'Meksiko 🇲🇽' },
  { value: 'mongolia',       label: 'Mongolia 🇲🇳' },
  { value: 'morocco',        label: 'Maroko 🇲🇦' },
  { value: 'netherlands',    label: 'Belanda 🇳🇱' },
  { value: 'new_zealand',    label: 'Selandia Baru 🇳🇿' },
  { value: 'norway',         label: 'Norwegia 🇳🇴' },
  { value: 'pakistan',       label: 'Pakistan 🇵🇰' },
  { value: 'philippines',    label: 'Filipina 🇵🇭' },
  { value: 'poland',         label: 'Polandia 🇵🇱' },
  { value: 'portugal',       label: 'Portugal 🇵🇹' },
  { value: 'qatar',          label: 'Qatar 🇶🇦' },
  { value: 'romania',        label: 'Romania 🇷🇴' },
  { value: 'russia',         label: 'Rusia 🇷🇺' },
  { value: 'saudi_arabia',   label: 'Arab Saudi 🇸🇦' },
  { value: 'seychelles',     label: 'Seychelles 🇸🇨' },
  { value: 'singapore',      label: 'Singapura 🇸🇬' },
  { value: 'slovakia',       label: 'Slovakia 🇸🇰' },
  { value: 'south_africa',   label: 'Afrika Selatan 🇿🇦' },
  { value: 'spain',          label: 'Spanyol 🇪🇸' },
  { value: 'sri_lanka',      label: 'Sri Lanka 🇱🇰' },
  { value: 'sudan',          label: 'Sudan 🇸🇩' },
  { value: 'sweden',         label: 'Swedia 🇸🇪' },
  { value: 'switzerland',    label: 'Swiss 🇨🇭' },
  { value: 'syria',          label: 'Suriah 🇸🇾' },
  { value: 'taiwan',         label: 'Taiwan 🇹🇼' },
  { value: 'thailand',       label: 'Thailand 🇹🇭' },
  { value: 'tunisia',        label: 'Tunisia 🇹🇳' },
  { value: 'turkey',         label: 'Turki 🇹🇷' },
  { value: 'uae',            label: 'Uni Emirat Arab 🇦🇪' },
  { value: 'ukraine',        label: 'Ukraina 🇺🇦' },
  { value: 'uk',             label: 'Inggris 🇬🇧' },
  { value: 'usa',            label: 'Amerika Serikat 🇺🇸' },
  { value: 'uzbekistan',     label: 'Uzbekistan 🇺🇿' },
  { value: 'venezuela',      label: 'Venezuela 🇻🇪' },
  { value: 'vietnam',        label: 'Vietnam 🇻🇳' },
  { value: 'other',          label: 'Negara Lainnya' },
]

export const INCOME_TYPES = [
  {
    value: 'technical_services',
    label: 'Jasa Teknis / Management Fee',
    description: 'Jasa konsultasi, manajemen, teknis, dan sejenisnya',
    icon: '🔧',
  },
  {
    value: 'royalties',
    label: 'Royalti',
    description: 'IP, merek dagang, paten, lisensi software',
    icon: '©️',
  },
  {
    value: 'dividends_general',
    label: 'Dividen <25%',
    description: 'Dividen dengan kepemilikan saham di bawah 25%',
    icon: '📊',
  },
  {
    value: 'dividends_qualified',
    label: 'Dividen ≥25%',
    description: 'Kepemilikan ≥25% selama 365+ hari (PMK 112 Pasal 20)',
    icon: '📈',
  },
  {
    value: 'interest',
    label: 'Bunga',
    description: 'Bunga pinjaman, obligasi, dan sejenisnya',
    icon: '💰',
  },
]

export const COUNTRY_FLAGS = {
  algeria:        '🇩🇿',
  australia:      '🇦🇺',
  austria:        '🇦🇹',
  bangladesh:     '🇧🇩',
  belgium:        '🇧🇪',
  brunei:         '🇧🇳',
  bulgaria:       '🇧🇬',
  canada:         '🇨🇦',
  china:          '🇨🇳',
  croatia:        '🇭🇷',
  czech_republic: '🇨🇿',
  denmark:        '🇩🇰',
  egypt:          '🇪🇬',
  finland:        '🇫🇮',
  france:         '🇫🇷',
  germany:        '🇩🇪',
  hong_kong:      '🇭🇰',
  hungary:        '🇭🇺',
  india:          '🇮🇳',
  iran:           '🇮🇷',
  italy:          '🇮🇹',
  japan:          '🇯🇵',
  jordan:         '🇯🇴',
  south_korea:    '🇰🇷',
  north_korea:    '🇰🇵',
  kuwait:         '🇰🇼',
  luxembourg:     '🇱🇺',
  malaysia:       '🇲🇾',
  mexico:         '🇲🇽',
  mongolia:       '🇲🇳',
  morocco:        '🇲🇦',
  netherlands:    '🇳🇱',
  new_zealand:    '🇳🇿',
  norway:         '🇳🇴',
  pakistan:       '🇵🇰',
  philippines:    '🇵🇭',
  poland:         '🇵🇱',
  portugal:       '🇵🇹',
  qatar:          '🇶🇦',
  romania:        '🇷🇴',
  russia:         '🇷🇺',
  saudi_arabia:   '🇸🇦',
  seychelles:     '🇸🇨',
  singapore:      '🇸🇬',
  slovakia:       '🇸🇰',
  south_africa:   '🇿🇦',
  spain:          '🇪🇸',
  sri_lanka:      '🇱🇰',
  sudan:          '🇸🇩',
  sweden:         '🇸🇪',
  switzerland:    '🇨🇭',
  syria:          '🇸🇾',
  taiwan:         '🇹🇼',
  thailand:       '🇹🇭',
  tunisia:        '🇹🇳',
  turkey:         '🇹🇷',
  uae:            '🇦🇪',
  ukraine:        '🇺🇦',
  uk:             '🇬🇧',
  usa:            '🇺🇸',
  uzbekistan:     '🇺🇿',
  venezuela:      '🇻🇪',
  vietnam:        '🇻🇳',
  other:          '🌍',
}

export const COUNTRY_LABELS = {
  algeria:        'Aljazair',
  australia:      'Australia',
  austria:        'Austria',
  bangladesh:     'Bangladesh',
  belgium:        'Belgia',
  brunei:         'Brunei',
  bulgaria:       'Bulgaria',
  canada:         'Kanada',
  china:          'Tiongkok',
  croatia:        'Kroasia',
  czech_republic: 'Republik Ceko',
  denmark:        'Denmark',
  egypt:          'Mesir',
  finland:        'Finlandia',
  france:         'Prancis',
  germany:        'Jerman',
  hong_kong:      'Hong Kong',
  hungary:        'Hungaria',
  india:          'India',
  iran:           'Iran',
  italy:          'Italia',
  japan:          'Jepang',
  jordan:         'Yordania',
  south_korea:    'Korea Selatan',
  north_korea:    'Korea Utara',
  kuwait:         'Kuwait',
  luxembourg:     'Luksemburg',
  malaysia:       'Malaysia',
  mexico:         'Meksiko',
  mongolia:       'Mongolia',
  morocco:        'Maroko',
  netherlands:    'Belanda',
  new_zealand:    'Selandia Baru',
  norway:         'Norwegia',
  pakistan:       'Pakistan',
  philippines:    'Filipina',
  poland:         'Polandia',
  portugal:       'Portugal',
  qatar:          'Qatar',
  romania:        'Romania',
  russia:         'Rusia',
  saudi_arabia:   'Arab Saudi',
  seychelles:     'Seychelles',
  singapore:      'Singapura',
  slovakia:       'Slovakia',
  south_africa:   'Afrika Selatan',
  spain:          'Spanyol',
  sri_lanka:      'Sri Lanka',
  sudan:          'Sudan',
  sweden:         'Swedia',
  switzerland:    'Swiss',
  syria:          'Suriah',
  taiwan:         'Taiwan',
  thailand:       'Thailand',
  tunisia:        'Tunisia',
  turkey:         'Turki',
  uae:            'Uni Emirat Arab',
  ukraine:        'Ukraina',
  uk:             'Inggris',
  usa:            'Amerika Serikat',
  uzbekistan:     'Uzbekistan',
  venezuela:      'Venezuela',
  vietnam:        'Vietnam',
  other:          'Negara Lainnya',
}

export const INCOME_LABELS = {
  technical_services:  'Jasa Teknis / Management Fee',
  royalties:           'Royalti',
  dividends_general:   'Dividen <25%',
  dividends_qualified: 'Dividen ≥25%',
  interest:            'Bunga',
}
